### PR TITLE
Dispatching exceptions via a delegate

### PR DESCRIPTION
**Pull request by om-moda**

### CODE REVIEW

**Comment by reppners** [comment]
Can you give a hint on when this PR may be merged? Our application enters production state soon and we need this among some other issues solved.

**Comment by tekhedd** [comment]
I'm guessing scottoffen has become "busy"? I am several weeks away from a release and am planning to do a release on my own fork for now because depend on some enhancements and fixes. Your changes fit with my program (I like the error log stuff, although I don't understand the need for server tags?). 

It may be necessary to create some releases using a fork until fearless leader returns?

**Comment by om-moda** [comment]
The server tags are actually just a plain object you can attach and receive. Slightly more elegant solution to use a singleton to access context stuff. May or may not be useful for others, however, it helps oru case.

**Comment by tekhedd** [comment]
Well, I definitely like all of your changes (I think the tag could replace my need for a global method for all the entry points, whether it's useful I have no idea). They merge with minimal conflict (but not automatically?) with the changes I'm proposing. (Still hoping to get some feedback but I find them to greatly simplify my handlers.

ventkaperi's Priority enhancement conflicts with my changes; I'd be happy to merge if mine are accepted. Priority is definitely a feature I would like to see for performance reasons.

**Comment by tekhedd** [comment]
Note when merging code: ProcessRequest must not call FireException if FireException throws, unless it then catches the exception. Otherwise the request processor thread will exit, and eventually you will run out of Workers. I will code around this in my merge.

I was wondering: why is there an exception handler in QueueRequest if all it does is immediately propagate up one level to HandleRequests()? Same "must catch all exceptions" issue applies to HandleRequests() as well of course.

**Comment by tekhedd** [comment]
I have merged all outstanding PRs as far as I can tell into tekhedd/Interspecific enhancements-merge branch. It seems to work without problems but I am not using most of the new features yet. Whee.

**Comment by scottoffen** [comment]
I've been swamped with the day job, just logged in after some time away an noticed the conversations. I'll go through the tickets this week and the PR and see if I can't get a new release out on Nuget this week or next.

**Pull request closed without merging**
